name: flutterapp
description: A new Flutter project.
publish_to: none
version: 1.0.0+1
environment:
  sdk: '>=3.0.0'
dependencies:
  animated_theme_switcher: ^2.0.3
  another_flushbar: ^1.10.29
  envied: ^0.5.2
  
  awesome_dio_interceptor: ^1.0.0
  cached_network_image: ^3.3.0
 
  change_app_package_name: ^1.1.0
  connectivity: ^3.0.6
  cupertino_icons: ^1.0.5
  dio: ^5.4.0
  dio_cache_interceptor: ^3.3.0
  dio_cache_interceptor_hive_store: ^3.2.0
  equatable: ^2.0.3
  
  eva_icons_flutter: ^3.1.0
  flutter_cache_manager: ^3.3.0
  flutter_riverpod: ^2.3.2
  flutter_screenutil: ^5.9.0
  flutter_staggered_animations: ^1.1.1
  font_awesome_flutter: ^10.1.0
  
  
 
  get_it: ^7.2.0
  get_storage: null
  google_fonts: ^4.0.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  
  intl: ^0.18.0 
  
  loading_overlay: ^0.3.0
  logger: ^1.1.0
 
 
  path: ^1.8.3
  path_provider: ^2.1.1
  provider: ^6.0.3
  
  youtube_player_flutter: ^8.1.2
  sentry_dio: ^7.2.0
  sentry_flutter: ^7.13.2
  
  shimmer: ^2.0.0
 

  slang: ^3.14.0
  slang_flutter: ^3.14.0
  
  stacked: ^3.4.0
  
 
  stacked_services: ^1.3.0

  hooks_riverpod: ^2.3.2

  
  
  
  flutter_localizations:
    sdk: flutter
  
  

dev_dependencies:
  build_runner: ^2.2.0
  flutter_launcher_icons: 
 
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.0




flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/animations/
    
  #  - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
